-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Campaigns (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  campaign_id text NOT NULL UNIQUE,
  campaign_name text NOT NULL,
  platform text NOT NULL,
  client_id bigint NOT NULL,
  sent integer,
  contacted integer,
  opens integer,
  replies integer,
  bounced integer,
  interested integer,
  status text,
  client_name text,
  CONSTRAINT Campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_client id_foreign FOREIGN KEY (client_id) REFERENCES public.Clients(id)
);
CREATE TABLE public.Clients (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Domain text NOT NULL UNIQUE,
  Company Name text NOT NULL,
  Primary Email text,
  Primary Number text,
  Contact Title text,
  Industry text,
  Services text,
  Onboarding Date date DEFAULT now(),
  instantly_api text,
  bison_api text,
  instantly_api_v2 text,
  CONSTRAINT Clients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Companies (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  Name text DEFAULT ''::text,
  Industry text,
  Domain text UNIQUE,
  Linkedin text,
  Linkedin Info text,
  Website Info text,
  Headcount bigint,
  City bigint,
  State bigint,
  Country bigint,
  CONSTRAINT Companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.Leads (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  Email text NOT NULL UNIQUE,
  First Name text,
  Last Name text,
  Linkedin URL text,
  Title text,
  Company ID bigint,
  Email Status text,
  Personal Email text,
  File_ID bigint,
  Custom_Fields jsonb,
  reply_status boolean,
  reply_intent text,
  bounce_status boolean,
  Industry text,
  reply_date date,
  client_id bigint,
  campaign_id bigint,
  reply_intent_changed text,
  address text,
  phone text,
  company_domain text,
  company_name text,
  internal_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  bison_lead_id bigint,
  instantly_lead_id bigint,
  lead_mx_provider text,
  CONSTRAINT Leads_pkey PRIMARY KEY (id, internal_id),
  CONSTRAINT Leads_Company ID_fkey FOREIGN KEY (Company ID) REFERENCES public.Companies(id),
  CONSTRAINT leads_company id_foreign FOREIGN KEY (Company ID) REFERENCES public.Companies(id),
  CONSTRAINT Leads_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.Clients(id),
  CONSTRAINT Leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.Campaigns(id)
);
CREATE TABLE public.bison_campaigns (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  campaign_id smallint UNIQUE,
  name text,
  status text,
  emails_sent bigint,
  opened bigint,
  unique_opens bigint,
  replied bigint,
  unique_replies bigint,
  bounced bigint,
  unsubscribed bigint,
  interested bigint,
  total_leads_contacted bigint,
  total_leads bigint,
  max_emails_per_day smallint,
  max_new_leads_per_day smallint,
  plain_text boolean,
  can_unsubscribe boolean,
  unsubscribe_text text,
  bison_workspace_id bigint,
  CONSTRAINT bison_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT bison_campaigns_bison_workspace_id_fkey FOREIGN KEY (bison_workspace_id) REFERENCES public.bison_workspaces(id)
);
CREATE TABLE public.bison_replies (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  subject text,
  read boolean,
  interested boolean,
  automated_reply boolean,
  html_body text,
  text_body text,
  date_received timestamp with time zone,
  type text,
  lead_id text,
  lead_email text,
  lead_mx_provider text,
  campaign_id bigint,
  sent_email_id bigint,
  reply_timestamp timestamp with time zone,
  Lead_id bigint,
  inbox_id uuid,
  raw_message_id text UNIQUE,
  sending_tool_id text,
  CONSTRAINT bison_replies_pkey PRIMARY KEY (id),
  CONSTRAINT bison_replies_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.bison_campaigns(id),
  CONSTRAINT bison_replies_sent_email_id_fkey FOREIGN KEY (sent_email_id) REFERENCES public.bison_sends(id),
  CONSTRAINT bison_replies_Lead_id_fkey FOREIGN KEY (Lead_id) REFERENCES public.Leads(id),
  CONSTRAINT bison_replies_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES public.inboxes(id)
);
CREATE TABLE public.bison_sends (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  subject text,
  html_body text,
  text_body text,
  timestamp_sent timestamp with time zone,
  campaign_id bigint,
  lead_email text,
  Lead_id bigint,
  raw_message_id text,
  inbox_sender_account uuid,
  bison_email_id bigint UNIQUE,
  CONSTRAINT bison_sends_pkey PRIMARY KEY (id),
  CONSTRAINT bison_sends_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.bison_campaigns(id),
  CONSTRAINT bison_sends_Lead_id_fkey FOREIGN KEY (Lead_id) REFERENCES public.Leads(id),
  CONSTRAINT bison_sends_inbox_sender_account_fkey FOREIGN KEY (inbox_sender_account) REFERENCES public.inboxes(id)
);
CREATE TABLE public.bison_workspaces (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  personal_team boolean,
  main boolean,
  parent_id smallint,
  contact_upload_limit bigint,
  remaining_monthly_contacts bigint,
  total_monthly_contacts bigint,
  total_monthly_email_verification_credits bigint,
  remaining_monthly_email_verification_credits bigint,
  remaining_email_verification_credits bigint,
  total_email_verification_credits bigint,
  sender_email_limit bigint,
  warmup_limit bigint,
  sender_email_limit_disabled boolean,
  has_access_to_warmup boolean,
  has_access_to_healthcheck boolean,
  client_id bigint,
  CONSTRAINT bison_workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT bison_workspaces_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.Clients(id)
);
CREATE TABLE public.domains (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid,
  name text UNIQUE,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT domains_pkey PRIMARY KEY (id),
  CONSTRAINT domains_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.inboxes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  domain_id uuid DEFAULT gen_random_uuid(),
  email text UNIQUE,
  daily_send_limit text,
  send_count text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT inboxes_pkey PRIMARY KEY (id),
  CONSTRAINT inboxes_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES public.domains(id)
);
CREATE TABLE public.instantly_campaigns (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  campaign_id text UNIQUE,
  name text,
  status text,
  email_gap smallint,
  random_wait_max smallint,
  text_only boolean,
  daily_limit smallint,
  stop_on_reply boolean,
  daily_max_leads smallint,
  match_lead_esp boolean,
  workspace_id bigint,
  CONSTRAINT instantly_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT instantly_campaigns_backup_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.instantly_workspaces(id)
);
CREATE TABLE public.instantly_replies (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  instantly_email_id text,
  timestamp_created timestamp with time zone,
  timestamp_email timestamp with time zone,
  subject text,
  body_text text,
  body_html text,
  cc_address_email_list text,
  bcc_address_email_list text,
  sent_email bigint,
  campaign_id bigint,
  instantly_lead_email text,
  lead_mx_provider text,
  instantly_campaign_id text,
  missive_sentiment_analysis text,
  lead_id bigint,
  inbox_id uuid,
  raw_message_id text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  step bigint,
  variant bigint,
  computation_key text,
  CONSTRAINT instantly_replies_pkey PRIMARY KEY (id),
  CONSTRAINT instantly_replies_clean_sent_email_fkey FOREIGN KEY (sent_email) REFERENCES public.instantly_sends(id),
  CONSTRAINT instantly_replies_clean_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.instantly_campaigns(id),
  CONSTRAINT instantly_replies_clean_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES public.inboxes(id),
  CONSTRAINT instantly_replies_clean_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.Leads(id)
);
CREATE TABLE public.instantly_sends (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  instantly_email_id text,
  timestamp_created timestamp with time zone,
  timestamp_email timestamp with time zone,
  subject text,
  to_address_email_list text,
  body_text text,
  body_html text,
  cc_address_email_list text,
  bcc_address_email_list text,
  campaign_id bigint,
  instantly_campaign_id text,
  instantly_lead_email text,
  lead_mx_provider text,
  list_id text,
  lead_id text,
  ue_type text,
  raw_message_id text UNIQUE,
  Lead_id bigint,
  inbox_id uuid,
  step bigint,
  variant bigint,
  computation_key text,
  CONSTRAINT instantly_sends_pkey PRIMARY KEY (id),
  CONSTRAINT instantly_sends_clean_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.instantly_campaigns(id),
  CONSTRAINT instantly_sends_clean_Lead_id_fkey FOREIGN KEY (Lead_id) REFERENCES public.Leads(id),
  CONSTRAINT instantly_sends_clean_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES public.inboxes(id)
);
CREATE TABLE public.instantly_workspaces (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  workspace_id text,
  add_unsub_to_block boolean,
  default_opportunity_value smallint,
  org_client_domain text,
  client_id bigint,
  CONSTRAINT instantly_workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT instantly_workspaces_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.Clients(id)
);
CREATE TABLE public.list builder (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  keywords text,
  cities text,
  CONSTRAINT list builder_pkey PRIMARY KEY (id)
);
CREATE TABLE public.missive_replies (
  id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  inbox_id uuid,
  lead_id bigint,
  bison_reply_id bigint,
  instantly_reply_id bigint,
  subject text,
  preview text,
  delivered_at timestamp with time zone,
  raw_message_id text UNIQUE,
  sentiment text,
  lead_category text,
  CONSTRAINT missive_replies_pkey PRIMARY KEY (id),
  CONSTRAINT missive_replies_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES public.inboxes(id),
  CONSTRAINT missive_replies_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.Leads(id),
  CONSTRAINT missive_replies_bison_reply_id_fkey FOREIGN KEY (bison_reply_id) REFERENCES public.bison_replies(id),
  CONSTRAINT missive_replies_instantly_reply_id_fkey FOREIGN KEY (instantly_reply_id) REFERENCES public.instantly_replies(id)
);
CREATE TABLE public.missive_sends (
  id uuid NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_id bigint,
  inbox_id uuid,
  bison_send_id bigint,
  instantly_send_id bigint,
  subject text,
  preview text,
  type text,
  delivered_at text,
  missive_updated_at timestamp with time zone,
  missive_created_at timestamp with time zone,
  raw_message_id text,
  from_email text,
  to_email text,
  CONSTRAINT missive_sends_pkey PRIMARY KEY (id),
  CONSTRAINT missive_sends_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.Leads(id),
  CONSTRAINT missive_sends_inbox_id_fkey FOREIGN KEY (inbox_id) REFERENCES public.inboxes(id),
  CONSTRAINT missive_sends_bison_send_id_fkey FOREIGN KEY (bison_send_id) REFERENCES public.bison_sends(id)
);
CREATE TABLE public.personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id bigint,
  name text,
  status text,
  group text,
  provider text,
  email_type text,
  daily_send_capacity text,
  previous_day_sent text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  uuid uuid DEFAULT gen_random_uuid(),
  CONSTRAINT personas_pkey PRIMARY KEY (id),
  CONSTRAINT personas_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.Clients(id)
);